module.exports = {
  taipei: '台北',
  newtaipei: '新北',
  taoyuan: '桃園',
  taichung: '台中',
  tainan: '台南',
  kaohsiung: '高雄',
  keelung: '基隆',
  hsinchu: '新竹',
  miaoli: '苗栗',
  changhua: '彰化',
  nantou: '南投',
  yunlin: '雲林',
  chiayi: '嘉義',
  pingtung: '屏東',
  yilan: '宜蘭',
  hualien: '花蓮',
  taitung: '台東',
  penghu: '澎湖'
};
